<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Kepribadian;

class KepribadianSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Kepribadian::create(['gambar'=>'estj.png','type'=>'ESTJ','kepribadian'=>'Tipe Realis Bertekad','deskripsi'=>'Kamu seorang yang extrovert yang merasakan dengan menggunakan pengindra atau sensing, membuat keputusan dan menarik kesimpulan dengan cara berpikir atau thinking serta melihat dunia luar dengan cara melakukan sebuah penilaian atau judging. Seseorang sepertimu merupakan individu yang mampu mengorganisir kegiatan dengan baik, mampu memanfaatkan sumber dan waktu secara efektif, fokus pada penyelesaian masalah, suka akan mengorganisir dan menjalankan aktivitas, pekerja keras namun cenderung kaku dan suka menuntut, kurang sabar serta memiliki sikap konsisten, pragmatis dan logis.',]);
        Kepribadian::create(['gambar'=>'entj.png','type'=>'ENTJ','kepribadian'=>'Tipe Pemikir Dinamis','deskripsi'=>'Kamu seorang yang extrovert yang merasakan dengan menggunakan intuitif (intuitive), membuat keputusan dan menarik kesimpulan dengan cara berpikir atau thinking serta melihat dunia luar dengan cara melakukan penilaian atau judging. Seseorang sepertimu merupakan individu yang mampu berpikir secara analitis, logis dan inovatif, orang entj mampu memecahkan masalah yang kompleks sekalipun karena melihat masalah sebagai tantangan yang harus dihadapi, memiliki kemampuan menjadi seorang pemimpin, suka berterus terang secara langsung dan ambisius, merupakan orang yang pekerja keras dan menyukai situasi kompetitif, individu entj adalah seorang yang terorganisir dan menyukai pekerjaan yang terjadwal dan beraturan.',]);
        Kepribadian::create(['gambar'=>'esfj.png','type'=>'ESFJ','kepribadian'=>'Tipe Realis Sosial','deskripsi'=>'Kamu seorang yang extrovert yang merasakan dengan menggunakan pengindra atau sensing, membuat keputusan dan menarik kesimpulan dengan melibatkan perasaan atau feeling serta melihat dunia luar dengan melakukan penilaian atau judging. Seseorang sepertimu merupakan individu yang terorganisir dan selalu berusaha menyelesaikan pekerjaannya dengan baik, menyukai pekerjaan yang rutin dan terjadwal, merupakan orng yang teratur dan efesien, orang dengan tipe kepribadian esfj adalah orang yang kooperatif dan senang bekerja dalam kelompok namun kurang menyukaihal-hal teoritis, merupakan orang yang hangat dan menyenangkan dalam berinteraksi dengan orang lain.',]);
        Kepribadian::create(['gambar'=>'enfj.png','type'=>'ENFJ','kepribadian'=>'Tipe Idealis Terlibat','deskripsi'=>'Kamu seorang yang extrovert yang merasakan dengan menggunakan intuitif (intuitive), membuat keputusan dan menarik kesimpulan dengan media perasaan atau feeling serta melihat dunia luar dengan melakukan penilaian atau (judging). Seseorang sepertimu merupakan individu yang ambisius dan pekerja keras, teratur dan berorientasi pada tujuan, bertanggung jawab, diplomatis dan berorientasi pada hasil namun cenderung tergesa-gesa dalam menyelesaikan sesuatu, dengan tipe kepribadian enfj merupakan individu yang penuh akan rasa empati, hangat dan suka menolong orang lain, mampu memotivasi orang lain dan mempelopori atau memulai suatu kegiatan, kemudian yang terakhir adalah mampu menghargai pendapat orang lain.',]);
        Kepribadian::create(['gambar'=>'estp.png','type'=>'ESTP','kepribadian'=>'Tipe Pelaku Bersemangat','deskripsi'=>'Kamu seorang yang extrovert yang merasakan dengan menggunakan pengindra atau sensing, membuat keputusan dan menarik kesimpulan dengan cara berpikir (thinking) serta melihat dunia luar dengan melakukan pengamatan (perceiving). Seseorang sepertimu merupakan orang yang terkenal paling realitis, pragmatis dan bekerja berdasarkan dengan fakta, berorientasi pada hasil, mampu menerima dan mengingat dalam banyak informasi. Orang dengan tipe kepribadian ini merupakan orang yang mampu bekerja di bawah tekanan dan menyukai sesuatu yang beresiko, memiliki tantangan san situasi kompetitif karena menganggap tantangan sebagai hal yang justri dihadapi, bukan ditakutkan. Cenderung lebih suka dalam menyelesaikan tugas pada waktu yang mendekati deadline, seringkali berterus terang dan kurang sensitif.',]);
        Kepribadian::create(['gambar'=>'entp.png','type'=>'ENTP','kepribadian'=>'Tipe Pemikir Pendobrak','deskripsi'=>'Kamu seorang yang extrovert yang merasakan dengan menggunakan intuitif (intuitive), membuat keputusan dan menarik kesimpulan dengan cara berpikir (thinking) serta melihat dunia luar dengan melakukan pengamatan (perceiving). Seseorang sepertimu merupakan orang yang inovatif, kreatif dan menyukai perubahan, dapat mengerjakan beberapa hal dalam sekaligus dan kurang dapat berfokus pada satu hal saja. Orang dengan tipe kepribadian ini merupakan orang yang antusias, menarik dan mudah bergaul dengan siapa saja, menyukai perdebatan dan berani menghadapi resiko dengan mempertimbangkan kemungkinan yang terjadi.',]);
        Kepribadian::create(['gambar'=>'esfp.png','type'=>'ESFP','kepribadian'=>'Tipe Pelaku Santai','deskripsi'=>'Kamu seorang yang extrovert yang merasakan dengan menggunakan pengindra (sensing), membuat keputusan dan menarik kesimpulan dengan perasaan (feeling) serta melihat dunia luar dengan melakukan pengamatan (perceiving). Seseorang sepertimu merupakan orang yang menyukai perubahan dan variasi dalam setiap kegiatan yang dilakukan, lebih mudah untuk mengingat fakta daripada teori, mempunyai kebiasaan yaitu dengan mengerjakan tugas dengan mendekati batas waktu yang ditentukan dan cenderung ingin cepat dalam menyelesaikan tugas atau pekerjaan tersebut. Orang dengan tipe kepribadian ini merupakan orang yang kooperatif, mudah bergaul dan suka akan menolong orang lain dan mampu dalam memotivasi serta memberi semangat kepada orang lain.',]);
        Kepribadian::create(['gambar'=>'enfp.png','type'=>'ENFP','kepribadian'=>'Tipe Idealis Spontan','deskripsi'=>'Kamu seorang yang extrovert yang merasakan dengan menggunakan intuitif (intuitive), membuat keputusan dan menarik kesimpulan dengan perasaan (feeling) serta melihat dunia luar dengan melakukan pengamatan (perceiving). Seseorang sepertimu merupakan orang yang kreatif dan penuh akan ide-ide baru, merupakan orang yang cepat dalam menyelesaikan masalah, menyukai pekerjaan dalam kelompok atau kerja tim. Orang dengan tipe kepribadian ini merupakan orang yang suka menolong, dapat berempati dan berkomunikasi dengan baik, tipe orang yang cenderung kurang fokus dalam mengembangkan berbagai potensi yang terjadi dan merupakan tipe orang yang tidak menyukai pekerjaan secara rutin atau pekerjaan yang terlalu terstruktur.',]);
        Kepribadian::create(['gambar'=>'infp.png','type'=>'INFP','kepribadian'=>'Tipe Idealis Pemimpi','deskripsi'=>'Kamu seorang yang introvert yang merasakan dengan menggunakan intuitif (intuitive), membuat keputusan dan menarik kesimpulan dengan perasaan (feeling) serta melihat dunia luar dengan melakukan pengamatan (perceiving). Seseorang sepertimu merupakan orang yang idealis, sensitif dan kreatif, kurang menyukai aturan, jadwal dan deadline dan kurang menyukai situasi yang kompetitif. Orang dengan tipe kepribadian ini merupakan tipe orang yang sabar dalam mengerjakan tugas-tugas yang kompleks atau susah. Selalu melihat sesuatu dari berbagai sudut pandang, juga merupakan orang yang mudah berteman dan memiliki tingkat kesetiaan yang tinggi.',]);
        Kepribadian::create(['gambar'=>'isfp.png','type'=>'ISFP','kepribadian'=>'Tipe Pelaku Peka','deskripsi'=>'Kamu seorang yang introvert yang merasakan dengan menggunakan pengindra (sensing), membuat keputusan dan menarik kesimpulan dengan media perasaan (feeling) serta melihat dunia luar dengan melakukan pengamatan (perceiving). Seseorang sepertimu merupakan orang yang memiliki standar yang tinggi dalam bekerja, merupakan orang yang fleksibel dan mudah beradaptasi, cenderung sensitif terhadap adanya konflik dan menghindari perbedaan pendapat. Orang dengan tipe kepribadian ini merupakan orang yang tidak menyukai akan adanya peraturan dan struktur yang ketat. Isfp merupakan tipe kepribadian yang berorientasi pada saat ini yaitu apa yang bisa dikerjakan pada saat ini maka dikerjakan, adalah orang yang sabar, rendah hati dan mau menolong orang lain.',]);
        Kepribadian::create(['gambar'=>'intp.png','type'=>'INTP','kepribadian'=>'Tipe Pemikir Analitis','deskripsi'=>'Kamu seorang yang introvert yang merasakan dengan menggunakan intuitif (intuitive), membuat keputusan dan menarik kesimpulan dengan cara berpikir (thinking) serta melihat dunia luar dengan melakukan pengamatan (perceiving). Seseorang sepertimu merupakan orang yang bersikap analitis dan terampil dalam menyelesaikan sesuatu, mampu memecahkan masalah yang kompleks dan konseptual serta senang bekerja sendiri. Orang dengan tipe kepribadian ini merupakan orang yang memiliki rasa ingin tahu yang tinggi dan memiliki banyak ide, membuat standar pribadi dalam menyelesaikan sesuatu dan tidak terlalu menyukai keramaian dan basa basi.',]);
        Kepribadian::create(['gambar'=>'istp.png','type'=>'ISTP','kepribadian'=>'Tipe Pelaku Individualistis','deskripsi'=>'Kamu seorang yang introvert yang merasakan dengan menggunakan pengindra (sensing), membuat keputusan dan menarik kesimpulan dengan cara berpikir (thinking) serta melihat dunia luar dengan melakukan pengamatan (perceiving). Seseorang sepertimu merupakan orang yang logis, realitis dan praktis, lebih menyukai tindakan dibandingkan berbicara, juga menyukai tantangan serta mampu menangani situasi yang kritis. Adalah orang yang fokus pada inti dari permasalahan dan cenderung mengabaikan aturan dalam mencapai tujuannya. Tipe orang yang tidak suka diawasi dalam bekerja dan memilih bekerja sendiri.',]);
        Kepribadian::create(['gambar'=>'infj.png','type'=>'INFJ','kepribadian'=>'Tipe Idealis Penyelaras','deskripsi'=>'Kamu seorang yang introvert yang merasakan dengan menggunakan intuitif (intuitive), membuat keputusan dan menarik kesimpulan dengan perasaan (feeling) serta melihat dunia luar dengan melakukan penilaian (judging). Seseorang sepertimu merupakan kepribadian yang kreatif, original dan praktis, mereka selalu berhati-hati dalam bertindak dan memiliki pendirian yang tegas, mereka selalu berusaha mencari cara yang tepat agar dapat memberikan hasil yang terbaik. Orang dengan tipe kepribadian ini merupakan orang yang suka menuntut orang lain supaya memiliki standard yang sama dengan dirinya. Orang yang menyukai situasi tenang dan terorganisir untuk bekerja.',]);
        Kepribadian::create(['gambar'=>'isfj.png','type'=>'ISFJ','kepribadian'=>'Tipe Realis Baik Hati','deskripsi'=>'Kamu seorang yang introvert yang merasakan dengan pengindra (sensing), membuat keputusan dan menarik kesimpulan dengan media perasaan (feeling) serta melihat dunia luar dengan melakukan penilaian (judging). Seseorang sepertimu merupakan orang yang teliti, akurat dan selalu bersungguh-sunguh dalam mengerjakan sesuatu, mereka memiliki ingatan yang baik terhadap setiap detail. Orang yang mampu menyelesaikan tugas secara tepat waktu, mereka mengerjakan sesuatu secara bertahap dan fokus pada satu kegiatan. Disamping itu juga adalah orang yang setia, bertanggung jawab dan memiliki disiplin diri.',]);
        Kepribadian::create(['gambar'=>'intj.png','type'=>'INTJ','kepribadian'=>'Tipe Pemikir Mandiri','deskripsi'=>'Kamu seorang yang introvert yang merasakan dengan menggunakan intuitif (intuitive), membuat keputusan dan menarik kesimpulan dengan cara berpikir (thinking) serta melihat dunia luar dengan melakukan penilaian (judging). Seseorang sepertimu merupakan orang yang mandiri dan senang akan bekerja sendiri, teratur dan bertanggung jawab, juga dapat memecahkan masalah secara kreatif. Orang dengan tipe kepribadian ini merupakan orang yang memiliki ide serta gagasan ke depan dan cenderung teoritis namun disamping itu orang dengan tipe kepribadian ini adalah orang yang mudah merasa frustasi apabila tujuannya tidak dapat tercapai.',]);
        Kepribadian::create(['gambar'=>'istj.png','type'=>'ISTJ','kepribadian'=>'Tipe Realis Terpercaya','deskripsi'=>'Kamu seorang yang introvert yang merasakan dengan menggunakan pengindra (sensing), membuat keputusan dan menarik kesimpulan dengan cara berpikir (thinking) serta melihat dunia luar dengan melakukan penilaian (judging). Seseorang sepertimu merupakan orang yang praktis, logis dan realitis, lebih mudah mengingat informasi dalam bentuk fakta dan dapat mengerjakan sesuatu secara detail. Orang yang suka dalam bekerja sendiri dan membutuhkan petunjuk yang jelas dalam mengerjakan sesuatu. Pekerja keras dan dapat diandalkan, juga serius, pendiam serta cenderung kaku dan kurang fleksibel.',]);


    }
}
